# Generated by Django 4.0.1 on 2022-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
