# Generated by Django 4.0.1 on 2022-02-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_client_qq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sn', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
